### ISSUE TITLE
Logs View

### ISSUE THREAD

**Issue by TangoIndiaMango** [PC-Ngumoha/fitnex#11]
Nice work @PC-Ngumoha on the logview.

i'd like to ask Why are we keeping track of invalid Id's for the post method? And can't there be a better expression to return the output for the get?

**Comment by PC-Ngumoha** [comment]
Thanks for the applause @TangoIndiaMango . Here is my attempt to respond to your question:

- **i'd like to ask Why are we keeping track of invalid Id's for the post method?**, To be honest, that was not the original plan I had, I initially wrote the code like this:
 ```
   try:
            exercises = (Exercise.objects.get(id=e_id)
                         for e_id in exercise_ids)
        except Exercise.DoesNotExist:
            return Response({"message": "Invalid exercise ID"},
                            status=status.HTTP_400_BAD_REQUEST)

 ```
 But after some consideration, decided to make it more granular for development purposes. Is it a bad idea to do so?
 
 - **And can't there be a better expression to return the output for the get?**. I'm sure that there is a better way to write this expression. Particularly, I feel that I could also have placed the logic for filtering the logs returned into a seperate function and use the output returned from that instead. I wrote it like this because I was lazy. Do you think it's necessary to refactor that code ?

**Comment by PC-Ngumoha** [comment]
Alright, I'll close this issue right now, feel free to reopen it if you have more questions or issues on this.

**Comment by TangoIndiaMango** [comment]
i feel we don't need to keep track of invalid Id's we just throw an error that id dosen't exist.
Also, just add a comment above for that expression that should handle it. Possibly someone else going through it will know this what you're trying to get done. you can put it in a doc string if the comment needs to be long. Thank you
